config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#start'
  get '/home', to: 'microposts#home'
  get '/search', to: 'microposts#search'
  get  '/signup',  to: 'users#new'
  get '/users', to: 'users#index'
  get '/transacted', to: 'users#transacted'
  get '/bookmarks', to: 'bookmarks#show'
  get '/notifications', to: 'notifications#index'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users, path: '/', only: [:show, :destroy, :update, :edit] do
    member do
      get :following, :followers, :likes
    end
  end
  resources :users,               only: [:create, :new]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:show, :create, :destroy, :new] do
    resources :contents,          only: [:index, :show]
    resources :bookmarks,         only: [:create, :destroy]
    resources :likes,             only: [:create, :destroy]
  end
  resources :contents,            only: [:create, :destroy]
  resources :transaction_logs,    only: [:create]
  resources :point_histories,     only: [:create]
  resources :relationships,       only: [:create, :destroy]
  resources :rooms,               only: [:create, :show]
  resources :direct_messages,     only: [:create]
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
  validates_uniqueness_of :micropost_id, scope: :user_id
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @micropost = Micropost.find(params[:micropost_id])
    @like = Like.new(micropost_id: params[:micropost_id],
                     user_id: current_user.id)
    @like.save
    redirect_back(fallback_location: home_url)
    # respond_to do |format|
    #   format.html { redirect_back(fallback_location: home_url) }
    #   format.js
    # end
  end

  def destroy
    @like = Like.find_by(micropost_id: params[:micropost_id])
    @micropost = Micropost.find(@like.micropost_id)
    @like.destroy
    redirect_back(fallback_location: home_url)
    # respond_to do |format|
    #   format.html { redirect_back(fallback_location: home_url) }
    #   format.js
    # end
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<%= link_to micropost_likes_path(micropost), method: :post, class: "like", remote: true do %>
  <svg role="img" xmlns="http://www.w3.org/2000/svg" width="19px" height="19px" viewBox="0 0 23 23" aria-labelledby="favouriteIconTitle" stroke="#bfbfbf" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" fill="none" color="black"> <title id="favouriteIconTitle">Favourite</title> <path d="M12,21 L10.55,19.7051771 C5.4,15.1242507 2,12.1029973 2,8.39509537 C2,5.37384196 4.42,3 7.5,3 C9.24,3 10.91,3.79455041 12,5.05013624 C13.09,3.79455041 14.76,3 16.5,3 C19.58,3 22,5.37384196 22,8.39509537 C22,12.1029973 18.6,15.1242507 13.45,19.7149864 L12,21 Z"/> </svg>
  <span class="conut"><%= micropost.likes.count %></span>
<% end %>

app/views/likes/_like_form.html.erb
<div id="like_form_<%= micropost.id %>">
  <% if current_user.already_liked?(micropost) %>
    <%= render 'likes/unlike', micropost: micropost %>
  <% else %>
    <%= render 'likes/like', micropost: micropost %>
  <% end %>
</div>

app/views/likes/_unlike.html.erb
<%= link_to micropost_like_path(micropost, id: micropost.id),method: :delete, class: "like" do %>
  <svg role="img" xmlns="http://www.w3.org/2000/svg" width="19px" height="19px" viewBox="0 0 23 23" aria-labelledby="favouriteIconTitle" stroke="crimson" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" fill="crimson" color="black"> <title id="favouriteIconTitle">Favourite</title> <path d="M12,21 L10.55,19.7051771 C5.4,15.1242507 2,12.1029973 2,8.39509537 C2,5.37384196 4.42,3 7.5,3 C9.24,3 10.91,3.79455041 12,5.05013624 C13.09,3.79455041 14.76,3 16.5,3 C19.58,3 22,5.37384196 22,8.39509537 C22,12.1029973 18.6,15.1242507 13.45,19.7149864 L12,21 Z"/> </svg>
  <span class="conut" style="color:crimson;"><%= micropost.likes.count %></span>
<% end %>

app/views/likes/create.js.erb
$("#like_form_<%= @micropost.id %>").html("<%= escape_javascript(render 'likes/unlike', micropost: @micropost )) %>");

app/views/likes/destroy.js.erb
$("#like_form_<%= @micropost.id %>").html("<%= escape_javascript(render 'likes/like', micropost: @micropost )) %>");