config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#start'
  get '/home', to: 'microposts#home'
  get '/search', to: 'microposts#search'
  get  '/signup',  to: 'users#new'
  get '/users', to: 'users#index'
  get '/transacted', to: 'users#transacted'
  get '/bookmarks', to: 'bookmarks#show'
  get '/notifications', to: 'notifications#index'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users, path: '/', only: [:show, :destroy, :update, :edit] do
    member do
      get :following, :followers, :likes
    end
  end
  resources :users,               only: [:create, :new]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:show, :create, :destroy, :new] do
    resources :contents,          only: [:index, :show]
    resources :bookmarks,         only: [:create, :destroy]
    resources :likes,             only: [:create, :destroy]
  end
  resources :contents,            only: [:create, :destroy]
  resources :transaction_logs,    only: [:create]
  resources :point_histories,     only: [:create]
  resources :relationships,       only: [:create, :destroy]
  resources :rooms,               only: [:create, :show]
  resources :direct_messages,     only: [:create]
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  has_one_attached :header_image
  has_many :microposts,       dependent: :destroy
  has_many :entries,          dependent: :destroy
  has_many :direct_messages,  dependent: :destroy
  has_many :likes,            dependent: :destroy
  has_many :bookmarks,        dependent: :destroy
  has_many :point_histories,  dependent: :destroy
  has_many :transaction_buyer_logs, class_name: "TransactionLog", foreign_key: :buyer_id
  has_many :transaction_seller_logs, class_name: "TransactionLog", foreign_key: :seller_id
  has_many :rooms,            through: :entries
  has_many :liked_posts,      through: :likes, source: :micropost
  has_many :bookmark_posts,   through: :bookmarks, source: :micropost
  has_many :active_relationships,  class_name:  "Relationship",
                                   foreign_key: "follower_id",
                                   dependent:   :destroy
  has_many :following,             through: :active_relationships,
                                   source: :followed
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :followers,             through: :passive_relationships, 
                                   source: :follower
  has_many :active_notifications,  class_name: "Notification",
                                   foreign_key:"sender_id",
                                   dependent: :destroy
  has_many :passive_notifications, class_name: "Notification",
                                   foreign_key:"recipient_id",
                                   dependent: :destroy

  #Transactionのbuyer_id,seller_idを外部キーに．
  has_many :buy_transaction_logs,  class_name:  "TransactionLog",
                                   foreign_key: "buyer_id"
  has_many :sell_transaction_logs, class_name:  "TransactionLog",
                                   foreign_key: "seller_id"

  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  #[!]で直接emailの値を小文字にする．
  before_save { email.downcase! }
  validates :name,  presence: true, length: { maximum: 50 }, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    # 一方のブラウザでログアウトし， もう一方がログインで終了しても, このメソッドを適応（エラー）させないように.
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  # アカウントを有効にする
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
    # update_columnsは、モデルのコールバックやバリデーションが実行されない点がupdate_attributeと異なります
    # update_attribute(:activated,    true)
    # update_attribute(:activated_at, Time.zone.now)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest:  User.digest(reset_token), reset_sent_at: Time.zone.now)
    # update_attribute(:reset_digest,  User.digest(reset_token))
    # update_attribute(:reset_sent_at, Time.zone.now)
  end

  # パスワード再設定のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # パスワード再設定の期限が切れている場合はtrueを返す
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

  # ユーザーをフォローする
  def follow(other_user)
    following << other_user # <<演算子（Shovel Operator）で配列の最後に追記することができる
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  def followed_by?(other_user)
    followers.include?(other_user)
  end

  def transacted?(seller_content)
    self.buy_transaction_logs.exists?(content_id: seller_content.id)
  end

  def main_icon_avatar
    avatar.variant(resize_to_fill: [45, 45])
  end

  def sub_icon_avatar
    avatar.variant(resize_to_fill: [35, 35])
  end

  def to_param
    catena_id
  end

  def already_liked?(micropost)
    self.likes.exists?(micropost_id: micropost.id)
  end

  def already_marked?(micropost)
    self.bookmarks.exists?(micropost_id: micropost.id)
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["sender_id = ? and recipient_id = ? 
                                and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        recipient_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  private

    # メールアドレスをすべて小文字にする
    def downcase_email
      self.email = email.downcase
    end

    # 有効化トークンとダイジェストを作成および代入する
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #未ログインにアクセスさせない
  before_action :logged_in_user, only: [:edit, :update, :destroy, :folloeing, :followers, :index]
  #自分以外のユーザーにアクセスさせない
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroys
  #ログイン済みにアクセスさせない
  before_action :logged_out_user?, only: [:new, :create]

  def index
    @users = User.where(activated: true)
  end

  def show
    @user = User.find_by(catena_id: params[:id])
    @microposts = @user.microposts.page(params[:page])
    @trend_posts = Micropost.trend
    @likes = @user.likes.build
    redirect_to root_url and return unless @user.activated?

    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id #お互いのroom_idを取得
          end
        end
      end
      unless @isRoom #まだ共有のルームがなければインスタンスを生成
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def new
    @user = User.new
    @trend_posts = Micropost.trend
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "送信されたメールをご確認ください．"
      redirect_to root_url
      # flash[:success] = "cateへようこそ！"
      # redirect_to @user
      # = redirect_to user_url(@user)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find_by(catena_id: params[:id])
    @trend_posts = Micropost.trend
  end

  def update
    @user = User.find_by(catena_id: params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    user = User.find_by(catena_id: params[:id])
    user.destroy
    flash[:success] = "#{user.name}を削除しました"
    redirect_to users_url
  end

  def following
    @title = "フォロー"
    @user  = User.find_by(catena_id: params[:id])
    @users = @user.following.page(params[:page])
    @trend_posts = Micropost.trend
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id #お互いのroom_idを取得
          end
        end
      end
      unless @isRoom #まだ共有のルームがなければインスタンスを生成
        @room = Room.new
        @entry = Entry.new
      end
    end
    render 'show_follow'
  end

  def followers
    @title = "フォロワー"
    @user  = User.find_by(catena_id: params[:id])
    @users = @user.followers.page(params[:page])
    @trend_posts = Micropost.trend
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id #お互いのroom_idを取得
          end
        end
      end
      unless @isRoom #まだ共有のルームがなければインスタンスを生成
        @room = Room.new
        @entry = Entry.new
      end
    end
    render 'show_follow'
  end

  def likes
    @title = "いいね"
    @user  = User.find_by(catena_id: params[:id])
    @microposts = @user.liked_posts.page(params[:page])
    @trend_posts = Micropost.trend
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id #お互いのroom_idを取得
          end
        end
      end
      unless @isRoom #まだ共有のルームがなければインスタンスを生成
        @room = Room.new
        @entry = Entry.new
      end
    end
    render 'show_likes'
  end

  def transacted
    @title = "購入済み"
    @trend_posts = Micropost.trend
    @user  = User.find(current_user.id)
    @transaction_logs = TransactionLog.where(buyer_id: @user.id)
    @contents = Content.where(id: @transaction_logs.map(&:content_id)).page(params[:page])
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :catena_id,
                                :password_confirmation, :avatar, :header_image)
    end

    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find_by(catena_id: params[:id])
      redirect_to(home_url) unless current_user?(@user)
    end

    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォロー", class: "btn btn-outline-danger" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :ユーザー名 %>
  <%= f.text_field :name %>

  <%= f.label :catena_id, "Catena ID" %>
  <%= f.text_field :catena_id, placeholder: "15文字以下 半角英数字・記号(-_)" %>

  <%= f.label :メールアドレス %>
  <%= f.email_field :email %>

  <%= f.label :パスワード %>
  <%= f.password_field :password, placeholder: "6文字以上 半角英数字・記号(-_)" %>

  <%= f.label :パスワード確認 %>
  <%= f.password_field :password_confirmation, placeholder: "再度パスワードを入力" %>

  <% if logged_in? %>
    <%= f.label :プロフィール画像 %>
    <%= f.file_field :avatar %>
  <% end %>

  <%= f.submit yield(:button_text) %>
<% end %>

app/views/users/_message_form.html.erb
<% unless @user.id == current_user.id %>
  <% if (current_user.followed_by? @user) && (@user.followed_by? current_user)  %>
    <% if @isRoom == true %>
      <%= link_to room_path(@roomId), class: "chat_btn" do %>
        <svg role="img" xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" viewBox="0 0 24 24" aria-labelledby="envelopeAltIconTitle" stroke="#a8abb1" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" fill="none" color="#2329D6"> <title id="envelopeAltIconTitle">Envelope</title> <rect width="20" height="14" x="2" y="5"/> <path stroke-linecap="round" d="M2 5l10 9 10-9"/> </svg>
      <% end %>
    <% else %>
      <%= form_with model: @room, class: "chat_start" do |f| %>
        <%= fields_for @entry do |e| %>
          <%= e.hidden_field :user_id, value: @user.id %>
        <% end %>
        <%= f.submit "チャットを始める" %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
               html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "フォロー中", class: "btn btn-danger" %>
<% end %>

app/views/users/_user.html.erb
<li class=follow_user-wrap>
  <%= link_to user_path(user), class: "follow_user-link" do %><% end %>
  <div class="follow_user">
    <%= image_tag user.avatar.variant(resize_to_fill: [50, 50]), class: "hoge" if user.avatar.attached? %>
    <div class="follow_user_name">
      <span class="sub-title-font"><%= user.name %></span>
      <span class="id_font"><%= user.catena_id %></span>
    </div>
    <% if current_user.admin? && !current_user?(user) %>
      <%= link_to "delete", user, method: :delete,
                                    data: { confirm: "本当に削除しますか？" } %>
    <% end %>
    <% unless current_user?(user) %>
      <div id="follow_form">
        <% if current_user.following?(user) %>
          <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id),
                  html: { method: :delete }, remote: true) do |f| %>
          <%= f.submit "フォロー中", class: "btn btn-danger" %>
          <% end %>
        <% else %>
          <%= form_with(model: current_user.active_relationships.build, remote: true) do |f| %>
            <div><%= hidden_field_tag :followed_id, user.id %></div>
            <%= f.submit "フォロー", class: "btn btn-outline-danger" %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  <div>
</li>

app/views/users/edit.html.erb
<% provide(:title, "プロフィール編集") %>
<% provide(:button_text, '保存') %>

<div class="form-wrap">
  <div class="form-container">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>

<ul class="users">
  <%= render @users %>
</ul>

app/views/users/new.html.erb
<% provide(:title, '新規登録') %>
<% provide(:button_text, '登録') %>

<div class="form-wrap">
  <div class="form-container">
    <span class="title-font">アカウントを作成する</span>
    <div class="form-title-link">
      <%= link_to "ログイン", login_path, class: "login-link" %>
      <%= link_to "新規登録", signup_path, class: "signup-link now-link" %>
    </div>
    <div>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "#{@user.name} / 投稿") %>

<%= render 'shared/user_stats' %>

<% if @user.microposts.any? %>
  <div class="all-microposts">
    <ul class="microposts jscroll">
      <%= render @microposts %>
      <%= paginate @microposts %>
    </ul>
  </div>
<% end %>


<script>
  $(window).on('scroll', function() {
      scrollHeight = $(document).height();
      scrollPosition = $(window).height() + $(window).scrollTop();
      if ( (scrollHeight - scrollPosition) / scrollHeight <= 0.05) {
            $('.jscroll').jscroll({
              contentSelector: '.microposts',
              nextSelector: 'span.next:last a'
            });
      }
  });
</script>

app/views/users/show_follow.html.erb
<% provide(:title, "#{@user.name} / #{@title}") %>

<%= render 'shared/user_stats' %>

<% if @users.any? %>
  <ul class="follow_list">
    <%= render @users %>
    <%= paginate @users %>
  </ul>
<% end %>

app/views/users/show_likes.html.erb
<% provide(:title, "#{@user.name} / #{@title}した投稿") %>

<%= render 'shared/user_stats' %>

<% if @user.liked_posts.any? %>
  <div class="all-microposts">
    <ul class="microposts jscroll">
      <%= render @microposts %>
      <%= paginate @microposts %>
    </ul>
  </div>
<% end %>

<script>
  $(window).on('scroll', function() {
      scrollHeight = $(document).height();
      scrollPosition = $(window).height() + $(window).scrollTop();
      if ( (scrollHeight - scrollPosition) / scrollHeight <= 0.05) {
            $('.jscroll').jscroll({
              contentSelector: '.micropost',
              nextSelector: 'span.next:last a'
            });
      }
  });
</script>

app/views/users/transacted.html.erb
<% provide(:title, "#{@title}") %>
<% if @transaction_logs.any? %>
  <div class="all-contents" >
    <div class="jscroll transacted_contents-wrap">
      <span class="page-sub-title">購入したコンテンツの数: <%= current_user.transaction_buyer_logs.count %></span>
      <% @contents.each do |content| %>
        <%= render 'contents/transacted_content', content: content %>
      <% end %>
      <%= paginate @contents %>
    </div>
  </div>
<% else %>
  <span>購入したコンテンツはありません</span>
<% end %>

<script>
  $(window).on('scroll', function() {
      scrollHeight = $(document).height();
      scrollPosition = $(window).height() + $(window).scrollTop();
      if ( (scrollHeight - scrollPosition) / scrollHeight <= 0.05) {
            $('.jscroll').jscroll({
              contentSelector: '.transacted_contents-wrap',
              nextSelector: 'span.next:last a'
            });
      }
  });
</script>