config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#start'
  get '/home', to: 'microposts#home'
  get '/search', to: 'microposts#search'
  get  '/signup',  to: 'users#new'
  get '/users', to: 'users#index'
  get '/transacted', to: 'users#transacted'
  get '/bookmarks', to: 'bookmarks#show'
  get '/notifications', to: 'notifications#index'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users, path: '/', only: [:show, :destroy, :update, :edit] do
    member do
      get :following, :followers, :likes
    end
  end
  resources :users,               only: [:create, :new]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:show, :create, :destroy, :new] do
    resources :contents,          only: [:index, :show]
    resources :bookmarks,         only: [:create, :destroy]
    resources :likes,             only: [:create, :destroy]
  end
  resources :contents,            only: [:create, :destroy]
  resources :transaction_logs,    only: [:create]
  resources :point_histories,     only: [:create]
  resources :relationships,       only: [:create, :destroy]
  resources :rooms,               only: [:create, :show]
  resources :direct_messages,     only: [:create]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ul class="microposts jscroll">
   <%= render @feed_items %>
   <%= paginate @feed_items,
                 params: { controller: :microposts, action: :home } %>
  </ul>
<% end %>

<script>
  $(window).on('scroll', function() {
      scrollHeight = $(document).height();
      scrollPosition = $(window).height() + $(window).scrollTop();
      if ( (scrollHeight - scrollPosition) / scrollHeight <= 0.05) {
            $('.jscroll').jscroll({
              contentSelector: '.microposts',
              nextSelector: 'span.next:last a'
            });
      }
  });
</script>

app/views/shared/_micropost_form.html.erb
<%= form_with(model: @micropost, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "シェアする", class: "btn btn-primary" %>
  <span class="image">
    <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
  </span>
<% end %>

<script type="text/javascript">
  $("#micropost_image").bind("change", function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert("Maximum file size is 5MB. Please choose a smaller file.");
      $("#micropost_image").val("");
    }
  });
</script>

app/views/shared/_post_title.html.erb
<div class="title-info">
  <%= link_to user_path(micropost.user) do %>
    <%= image_tag micropost.user.main_icon_avatar, class: "user-icon"%>
  <% end %>
  <div class="title-status">
  <%= link_to micropost_contents_path(micropost_id: micropost.id) do %>
    <span class="post-title">
      <%= micropost.text %>
    </span>
  <% end %>
    <div class="user-info">
      <%= link_to micropost.user do %>
        <span class="user-name"><%= micropost.user.name %></span>
        <span class="user-id"><%= micropost.user.catena_id %></span>
      <% end %>
      <span class="post-time">
        ・ <%= time_ago_in_words(micropost.created_at) %>
      </span>
    </div>
  </div>
  <% if current_user?(micropost.user) %>
    <%= link_to "削除", micropost, method: :delete, data: { confirm: "削除しますか？" } %>
  <% end %>
  <div class="post-setting">
    <svg role="img" xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" viewBox="0 0 24 24" aria-labelledby="ellypsisIconTitle" stroke="#bfbfbf" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" fill="none" color="black"> <title id="ellypsisIconTitle">Ellypsis</title> <circle cx="12" cy="12" r="1"/> <circle cx="6" cy="12" r="1"/> <circle cx="18" cy="12" r="1"/> </svg>
  </div>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <span id="following" class="stat">
      <%= @user.following.count %>
    </span>
    フォロー
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <span id="followers" class="stat">
      <%= @user.followers.count %>
    </span>
    フォロワー
  </a>
</div>

app/views/shared/_trend_post.html.erb
<div class="sub-contents">
  <%= link_to micropost_contents_path(micropost_id: trend_post.id), class: "post-link" do %>
    <div class="trend-contents-wrap">
      <div class="trend-contents">
        <div class="title-info">
          <%= link_to user_path(trend_post.user) do %>
            <%= image_tag trend_post.user.sub_icon_avatar, class: "user-icon"%>
          <% end %>
          <div class="title-status">
            <%= link_to micropost_contents_path(micropost_id: trend_post.id) do %>
              <span class="post-title">
                <%= trend_post.text %>
              </span>
            <% end %>
            <div class="user-info">
              <%= link_to trend_post.user do %>
                <span class="user-name"><%= trend_post.user.name %></span>
                <span class="user-id"><%= trend_post.user.catena_id %></span>
              <% end %>
              <span class="post-time">
                ・ <%= time_ago_in_words(trend_post.created_at) %>
              </span>
            </div>
          </div>
        </div>
        <div class="trend-contents-img">
          <%= image_tag trend_post.right_container_image, class: "post-img" if trend_post.image.attached?%>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_user_stats.html.erb
<div class="mypage-wrap">
  <div class="mypage">
    <%= image_tag @user.avatar.variant(resize_to_fill: [140, 140]), class: "hoge" if @user.avatar.attached? %>
    <div class="user_info">
      <div class="user_info-top">
        <span class="sub-title-font"><%= @user.name %></span>
        <div class="user_action-form">
          <%= render 'follow_form' if logged_in? %>
          <%= render 'message_form' if logged_in? %>
          <% if current_user?(@user) %>
            <%= link_to "プロフィール編集", edit_user_path(current_user), class: "profile_edit-btn" %>
          <% end %>
        </div>
      </div>
      <div>
       <%= render 'shared/stats' %>
      </div>
    </div>
  </div>
  <div class="user_post">
    <%= link_to user_path(@user) do %>
      投稿(<%= @user.microposts.count %>)
    <% end %>
    <%= link_to likes_user_path(@user) do %>
      いいね(<%= @user.liked_posts.count %>)
    <% end %>
  </div>
</div>