config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#start'
  get '/home', to: 'microposts#home'
  get '/search', to: 'microposts#search'
  get  '/signup',  to: 'users#new'
  get '/users', to: 'users#index'
  get '/transacted', to: 'users#transacted'
  get '/bookmarks', to: 'bookmarks#show'
  get '/notifications', to: 'notifications#index'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users, path: '/', only: [:show, :destroy, :update, :edit] do
    member do
      get :following, :followers, :likes
    end
  end
  resources :users,               only: [:create, :new]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:show, :create, :destroy, :new] do
    resources :contents,          only: [:index, :show]
    resources :bookmarks,         only: [:create, :destroy]
    resources :likes,             only: [:create, :destroy]
  end
  resources :contents,            only: [:create, :destroy]
  resources :transaction_logs,    only: [:create]
  resources :point_histories,     only: [:create]
  resources :relationships,       only: [:create, :destroy]
  resources :rooms,               only: [:create, :show]
  resources :direct_messages,     only: [:create]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">Catena</a>
    by <a href="#">Kotaro Yamamoto</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><%= link_to "開発者", '#' %></li>
      <li>© 2020 Catena, Inc.<li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>

  <div class="header-box">
    <div class="side-header">
      <div class="header-items">
        <div class="header-top">
          <div class="site-logo">
            <%= link_to "Catena", home_path, class:"logo"%>
          </div>
        </div>

        <div class="nav-menu-items">
          <div class="nav-menu-icons">

            <% if logged_in? %>
              <%= link_to home_path, class:"nav-link" do %>
                <div>
                  <svg role="img" xmlns="http://www.w3.org/2000/svg" width="25px" height="25px" viewBox="0 0 24 24" aria-labelledby="homeAltIconTitle" stroke="#787c7b" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none" color="black"> <path d="M3 10.182V22h18V10.182L12 2z"/> <rect width="6" height="8" x="9" y="14"/> </svg>
                  <span class="nav-title">ホーム</span>
                </div>
              <% end %>

              <%= link_to "#", class:"nav-link" do %>
                <div>
                  <svg role="img" xmlns="http://www.w3.org/2000/svg" width="25px" height="25px" viewBox="0 0 24 24" aria-labelledby="starIconTitle" stroke="#787c7b" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none" color="black"> <polygon points="12 17.844 6.183 20.902 7.294 14.425 2.588 9.838 9.092 8.893 12 3 14.908 8.893 21.412 9.838 16.706 14.425 17.817 20.902"/> </svg>
                  <span class="nav-title">おすすめ</span>
                </div>
              <% end %>

              <%= link_to transacted_path, class:"nav-link" do %>
                <div>
                  <svg width="26px" height="26px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" aria-labelledby="layersIconTitle" stroke="#787c7b" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" color="#2329D6"> <title id="layersIconTitle">Layers</title> <path d="M12 4L20 8.00004L12 12L4 8.00004L12 4Z"/> <path d="M20 12L12 16L4 12"/> <path d="M20 16L12 20L4 16"/> </svg>
                  <span class="nav-title">購入済み</span>
                </div>
              <% end %>

              <%= link_to bookmarks_path, class:"nav-link" do %>
                <div>
                  <svg role="img" xmlns="http://www.w3.org/2000/svg" width="26px" height="26px" viewBox="0 0 24 24" aria-labelledby="bookmarkIconTitle" stroke="#787c7b" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none" color="black"> <title id="bookmarkIconTitle">Bookmark</title> <path d="M17,6.65881537 L17,19.5857864 L12,16.4078051 L7,19.5857864 L7,6.65881537 C7,5.19039219 8.11928813,4 9.5,4 L14.5,4 C15.8807119,4 17,5.19039219 17,6.65881537 Z"/> </svg>
                  <span class="nav-title">ブックマーク</span>
                </div>
              <% end %>

              <%= link_to current_user, class:"nav-link" do %>
                <div>
                  <svg role="img" xmlns="http://www.w3.org/2000/svg" width="26px" height="26px" viewBox="0 0 24 24" aria-labelledby="personIconTitle" stroke="#787c7b" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none" color="#2329D6"> <title id="personIconTitle">Person</title> <path d="M4,20 C4,17 8,17 10,15 C11,14 8,14 8,9 C8,5.667 9.333,4 12,4 C14.667,4 16,5.667 16,9 C16,14 13,14 14,15 C16,17 20,17 20,20"/> </svg>
                  <span class="nav-title">マイページ</span>
                </div>
              <% end %>

              <%= link_to notifications_path, class:"nav-link right-none" do %>
                <div >
                <svg role="img" xmlns="http://www.w3.org/2000/svg" width="25px" height="25px" viewBox="0 0 24 24" aria-labelledby="bellIconTitle" stroke="#787c7b" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none" color="black"> <path stroke-linejoin="round" d="M10.5,4.5 C12.1666667,4.5 13.8333333,4.5 15.5,4.5 C17.5,4.5 18.8333333,3.83333333 19.5,2.5 L19.5,18.5 C18.8333333,17.1666667 17.5,16.5 15.5,16.5 C13.8333333,16.5 12.1666667,16.5 10.5,16.5 L10.5,16.5 C7.1862915,16.5 4.5,13.8137085 4.5,10.5 L4.5,10.5 C4.5,7.1862915 7.1862915,4.5 10.5,4.5 Z" transform="rotate(90 12 10.5)"/> <path d="M11,21 C12.1045695,21 13,20.1045695 13,19 C13,17.8954305 12.1045695,17 11,17" transform="rotate(90 12 19)"/> </svg>
                  <span class="nav-title">通知</span>
                </div>
              <% end %>

              <%= link_to search_path, class:"nav-link right-none" do %>
                <div>
                <svg class="search"  role="img" xmlns="http://www.w3.org/2000/svg" width="25px" height="25px" viewBox="0 0 24 24" aria-labelledby="searchIconTitle" stroke="#787c7b" stroke-width="2" stroke-linecap="square" stroke-linejoin="miter" fill="none" color="black"><path d="M14.4121122,14.4121122 L20,20"/> <circle cx="10" cy="10" r="6"/> </svg>
                  <span class="nav-title">検索</span>
                </div>
              <% end %>

              <%= link_to current_user, class:"nav-link right-none" do %>
                <div>
                <svg role="img" xmlns="http://www.w3.org/2000/svg" width="23px" height="23px" viewBox="0 0 24 24" aria-labelledby="envelopeAltIconTitle" stroke="#787c7b" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none" color="#2329D6"> <title id="envelopeAltIconTitle">Envelope</title> <rect width="20" height="14" x="2" y="5"/> <path stroke-linecap="round" d="M2 5l10 9 10-9"/> </svg>
                  <span class="nav-title">メッセージ</span>
                </div>
              <% end %>

              <div class="btn right-none">
                <%= link_to new_micropost_path do %>
                  <svg xmlns="http://www.w3.org/2000/svg" width="19px" height="19px" viewBox="0 0 24 24"><path d="M5 4h-3v-1h3v1zm12 9c0 2.206-1.794 4-4 4s-4-1.794-4-4 1.794-4 4-4 4 1.794 4 4zm-1 0c0-1.657-1.342-3-3-3s-3 1.343-3 3 1.342 3 3 3 3-1.343 3-3zm8-8v17h-24v-17h5.93c.669 0 1.293-.334 1.664-.891l1.406-2.109h8l1.406 2.109c.371.557.995.891 1.664.891h3.93zm-19 4c0-.552-.447-1-1-1s-1 .448-1 1 .447 1 1 1 1-.448 1-1zm14 4c0-3.314-2.687-6-6-6s-6 2.686-6 6 2.687 6 6 6 6-2.686 6-6z"/></svg>
                  <span>投 稿</span>
                <% end %>
              </div>
              
            <% else %>
              <%= link_to "#", class:"nav-link" do %>
                <div>
                  <svg role="img" xmlns="http://www.w3.org/2000/svg" width="25px" height="25px" viewBox="0 0 24 24" aria-labelledby="starIconTitle" stroke="#787c7b" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none" color="black"> <polygon points="12 17.844 6.183 20.902 7.294 14.425 2.588 9.838 9.092 8.893 12 3 14.908 8.893 21.412 9.838 16.706 14.425 17.817 20.902"/> </svg>
                  <span class="nav-title">おすすめ</span>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
          <nav>
          <ul>
            <li><%= link_to "ユーザー", users_path %></li>
            <% if logged_in? %>
              <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
            <% end %>
          </ul>
      </div>
    </div>
  </div>
<%
=begin
%>

<-------------------お気に入りユーザー機能---実装予定-------------------->

      <div class="favorite-users-title">
        <a href="#">
          <svg role="img" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path d="M6.166 16.943l1.4 1.4-4.622 4.657h-2.944l6.166-6.057zm11.768-6.012c2.322-2.322 4.482-.457 6.066-1.931l-8-8c-1.474 1.584.142 3.494-2.18 5.817-3.016 3.016-4.861-.625-10.228 4.742l9.6 9.6c5.367-5.367 1.725-7.211 4.742-10.228z"/></svg>
          <span>お気に入りユーザー</span>
        </a>
      </div>
      <div class="favorite-users">
        <a href="#">
          <%= image_tag 'kazetachinu049.jpg', class:'user-icon' %>
          <div class="user-status">
            <div class="user-info">
              <span>ユーザーネーム</span>
              <span>(@username)</span>
            </div>
            <span>シン・エヴァンゲリオン見てきた</span>
          </div>
        </a>
      </div>
<%
=end
%>
  
</header>

app/views/layouts/_main.html.erb
<main>
  <div class="main-container">
    <div class="top-nav">
      <div class="page-title">
        <a href="#">
          <span>ホーム</span>
        </a>
      </div>
    </div>
    <div class="all-microposts">
    
      <div class="micropost">
        <a href="##" class="post-link"></a>
        <div class="post">
          
          <%= image_tag 'ajisai.jpg', class:'post-img' %>
          <div class="post-document">
            <div class="title-info">
              <a href="#">
                <%= image_tag 'kazetachinu049.jpg', class:'user-icon' %>
              </a>
              <div class="title-status">
                <span class="title">この梅雨の湿気の中で泳ぐ</span>
                <div class="user-info">
                  <a href="#">
                    <span class="user-name">山田太郎</span>
                    <span class="user-id">(@userid)</span>
                  </a>
                  <span class="post-time">・56分</span>
                </div>
              </div>
              <div class="post-setting">
                <svg role="img" xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" viewBox="0 0 24 24" aria-labelledby="ellypsisIconTitle" stroke="#bfbfbf" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" fill="none" color="black"> <title id="ellypsisIconTitle">Ellypsis</title> <circle cx="12" cy="12" r="1"/> <circle cx="6" cy="12" r="1"/> <circle cx="18" cy="12" r="1"/> </svg>
              </div>
            </div>
            <ul>
              <li><a href="#" class="contents">撮影方法</a></li>
              <li><a href="#" class="contents">撮影方法</a></li>
              <li><a href="#" class="contents">撮影方法</a></li>
              <li><a href="#" class="contents">撮影方法</a></li>
              <li><a href="#" class="contents">撮影方法</a></li>
            </ul>
            <div class="micropost-status">
              <div class="hashtag-list">
                <a href="#" class="hashtag">#紫陽花</a>
                <a href="#" class="hashtag">#紫陽花</a>
                <a href="#" class="hashtag">#紫陽花</a>
                <a href="#" class="hashtag">#紫陽花</a>
                <a href="#" class="hashtag">#紫陽花</a>
                <a href="#" class="hashtag">#紫陽花</a>
                <a href="#" class="hashtag">#紫陽花</a>
                <a href="#" class="hashtag">#雨</a>
                <a href="#" class="hashtag">#傘</a>
              </div>
              <div class="post-status">
                <span>大阪</span>
                <div class="like">
                  <svg role="img" xmlns="http://www.w3.org/2000/svg" width="19px" height="19px" viewBox="0 0 23 23" aria-labelledby="favouriteIconTitle" stroke="#bfbfbf" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" fill="none" color="black"> <title id="favouriteIconTitle">Favourite</title> <path d="M12,21 L10.55,19.7051771 C5.4,15.1242507 2,12.1029973 2,8.39509537 C2,5.37384196 4.42,3 7.5,3 C9.24,3 10.91,3.79455041 12,5.05013624 C13.09,3.79455041 14.76,3 16.5,3 C19.58,3 22,5.37384196 22,8.39509537 C22,12.1029973 18.6,15.1242507 13.45,19.7149864 L12,21 Z"/> </svg>
                  <span class="conut">33</span>
                </div>
                <div>
                  <svg role="img" class="bookmark" xmlns="http://www.w3.org/2000/svg" width="22px" height="22px" viewBox="0 0 22 22" aria-labelledby="bookmarkIconTitle" stroke="#bfbfbf" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round" fill="none" color="black"> <title id="bookmarkIconTitle">Bookmark</title> <path d="M17,6.65881537 L17,19.5857864 L12,16.4078051 L7,19.5857864 L7,6.65881537 C7,5.19039219 8.11928813,4 9.5,4 L14.5,4 C15.8807119,4 17,5.19039219 17,6.65881537 Z"/> </svg>
                </div>
                <div>
                  <svg role="img" class="question" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" ><path d="M12 1c-6.338 0-12 4.226-12 10.007 0 2.05.738 4.063 2.047 5.625.055 1.83-1.023 4.456-1.993 6.368 2.602-.47 6.301-1.508 7.978-2.536 9.236 2.247 15.968-3.405 15.968-9.457 0-5.812-5.701-10.007-12-10.007zm0 15c-.565 0-1.024-.459-1.024-1.025 0-.565.459-1.024 1.024-1.024.566 0 1.024.459 1.024 1.024 0 .566-.458 1.025-1.024 1.025zm1.606-4.858c-.74.799-.775 1.241-.766 1.785h-1.643c-.006-1.208.016-1.742 1.173-2.842.469-.446.84-.799.788-1.493-.047-.66-.599-1.004-1.117-1.004-.581 0-1.261.432-1.261 1.649h-1.646c0-1.966 1.155-3.237 2.941-3.237.849 0 1.592.278 2.09.783.468.473.709 1.125.7 1.883-.013 1.134-.704 1.878-1.259 2.476z"/></svg>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      
      
    </div>
  </div>

  <%= render 'layouts/right_contents' %>

</main>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<meta name="viewport" content="width=device-width, initial-scale=1">

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jscroll/2.4.1/jquery.jscroll.min.js"></script>

app/views/layouts/_right_contents.html.erb
<div class="right-container">
  <div class="right-icon">
    <%= link_to search_path, class: "right-svg" do %>
      <svg class="search"  role="img" xmlns="http://www.w3.org/2000/svg" width="25px" height="25px" viewBox="0 0 24 24" aria-labelledby="searchIconTitle" stroke="#a8abb1" stroke-width="1.7" stroke-linecap="square" stroke-linejoin="miter" fill="none" color="black"><path d="M14.4121122,14.4121122 L20,20"/> <circle cx="10" cy="10" r="6"/> </svg>
    <% end %>
    <% if logged_in? %>
      <%= link_to notifications_path, class: "right-svg" do %>
        <svg role="img" xmlns="http://www.w3.org/2000/svg" width="25px" height="25px" viewBox="0 0 24 24" aria-labelledby="bellIconTitle" stroke="#a8abb1" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" fill="none" color="black"> <path stroke-linejoin="round" d="M10.5,4.5 C12.1666667,4.5 13.8333333,4.5 15.5,4.5 C17.5,4.5 18.8333333,3.83333333 19.5,2.5 L19.5,18.5 C18.8333333,17.1666667 17.5,16.5 15.5,16.5 C13.8333333,16.5 12.1666667,16.5 10.5,16.5 L10.5,16.5 C7.1862915,16.5 4.5,13.8137085 4.5,10.5 L4.5,10.5 C4.5,7.1862915 7.1862915,4.5 10.5,4.5 Z" transform="rotate(90 12 10.5)"/> <path d="M11,21 C12.1045695,21 13,20.1045695 13,19 C13,17.8954305 12.1045695,17 11,17" transform="rotate(90 12 19)"/> </svg>
      <% end %>
      <%= link_to notifications_path, class: "right-svg" do %>
        <svg role="img" xmlns="http://www.w3.org/2000/svg" width="23px" height="23px" viewBox="0 0 24 24" aria-labelledby="envelopeAltIconTitle" stroke="#a8abb1" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" fill="none" color="#2329D6"> <title id="envelopeAltIconTitle">Envelope</title> <rect width="20" height="14" x="2" y="5"/> <path stroke-linecap="round" d="M2 5l10 9 10-9"/> </svg>
      <% end %>
      <div class="my-icons">
        <%= link_to user_path(current_user) do %>
          <%= image_tag current_user.avatar, class: "user-icon"%>
        <% end %>
      </div>
      <div class="btn">
        <%= link_to new_micropost_path, class: "post-btn" do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="19px" height="19px" viewBox="0 0 24 24"><path d="M5 4h-3v-1h3v1zm12 9c0 2.206-1.794 4-4 4s-4-1.794-4-4 1.794-4 4-4 4 1.794 4 4zm-1 0c0-1.657-1.342-3-3-3s-3 1.343-3 3 1.342 3 3 3 3-1.343 3-3zm8-8v17h-24v-17h5.93c.669 0 1.293-.334 1.664-.891l1.406-2.109h8l1.406 2.109c.371.557.995.891 1.664.891h3.93zm-19 4c0-.552-.447-1-1-1s-1 .448-1 1 .447 1 1 1 1-.448 1-1zm14 4c0-3.314-2.687-6-6-6s-6 2.686-6 6 2.687 6 6 6 6-2.686 6-6z"/></svg>
          <span>投 稿</span>
        <% end %>
      </div>
    <% else %>
      <div class="btn">
        <%= link_to login_path, class: "right-login-btn" do %>
          <span>ログイン</span>
        <% end %>
      </div>
      <div class="btn">
        <%= link_to signup_path, class: "right-signup-btn" do %>
          <span>新規登録</span>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="sub-container">
    <div class="sub-container-title">
      <a class="btn-trending" href="#">トレンド</a>
      <a class="btn-popular-subscription" href="#">話題のサブスク</a>
    </div>

    <% @trend_posts.each do |trend_post| %>
      <%= render 'shared/trend_post', trend_post: trend_post %>
    <% end %>

  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <main>
      <div class="main-container">
        <div class="top-nav">
          <div class="page-title">
            <a href="#">
              <span><%= yield(:title) %></span>
            </a>
          </div>
        </div>
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
        <div class="container">
          <%= debug(params) if Rails.env.development? %>
          <%= yield %>
        </div>
      </div>
      <%= render 'layouts/right_contents' %>
    </main>
  </body>
</html>